server:
  port: 8888

profiles:
  active: native

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/codeactuator/rocket-config-repository
          search-paths:
                     - project-service


  application:
      name: config-server
